"""add gpa to cv

Revision ID: 5378db338fa7
Revises: 728cdb1eea9a
Create Date: 2026-04-05 06:08:37.399142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5378db338fa7'
down_revision: Union[str, Sequence[str], None] = '728cdb1eea9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv', sa.Column('gpa', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv', 'gpa')
    # ### end Alembic commands ###
