"""add DOB for applicant and opening_date for recrutier

Revision ID: b11220ec88c4
Revises: 5378db338fa7
Create Date: 2026-04-05 06:16:48.539166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11220ec88c4'
down_revision: Union[str, Sequence[str], None] = '5378db338fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant', sa.Column('data_of_birth', sa.Date(), nullable=True))
    op.add_column('recruiter', sa.Column('opening_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiter', 'opening_date')
    op.drop_column('applicant', 'data_of_birth')
    # ### end Alembic commands ###
