services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: rw-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "8386:5432"
    volumes:
      - datn_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rw-db"]
      interval: 10s
      timeout: 5s
      retries: 5

#   client:
#     build:
#       context: ..
#       dockerfile: docker/Dockerfile.client
#     container_name: datn-frontend
#     ports:
#       - "3001:3000"
#     volumes:
#       - ../client:/app
#       - /app/node_modules
#     environment:
#       - CHOKIDAR_USEPOLLING=true

# networks:
#   local-network-datn:
#     name: local-network-datn
#     driver: bridge

volumes:
  datn_pgdata: